// File generated by flutterfire init
import 'dart:io';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// `FirebaseOptions` configuration for each platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    if (Platform.isWeb) {
      return web;
    }
    if (Platform.isMacOS) {
      return macos;
    }
    if (Platform.isWindows) {
      return windows;
    }
    if (Platform.isLinux) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:android:8cedef083c90b53d9c9160',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:ios:9f8e7d6c5b4a3f2e1d0c',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.gumballz.shop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:web:abc123def456ghi789',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    authDomain: 'gumballzshop.firebaseapp.com',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:ios:9f8e7d6c5b4a3f2e1d0c',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.gumballz.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:web:abc123def456ghi789',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    authDomain: 'gumballzshop.firebaseapp.com',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDloQCkWvDUNziR0nlIje6sANBjPBIF5co',
    appId: '1:831997602337:web:abc123def456ghi789',
    messagingSenderId: '831997602337',
    projectId: 'gumballzshop',
    authDomain: 'gumballzshop.firebaseapp.com',
    databaseURL: 'https://gumballzshop.firebaseio.com',
    storageBucket: 'gumballzshop.appspot.com',
  );
}
